name: Build and lint

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  validation:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Build on Ubuntu
        run: npm run build
      - name: All generated code is commited
        run: |
          git update-index --refresh
          git diff-index --exit-code --name-status HEAD --

  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .github/files/.nvmrc
      - name: NodeJS version
        run: node -v
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
