name: Build and lint

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Print node js version
        run: node -v
      - name: Build
        run: yarn build


# Unable to find Node version '14' for platform darwin and architecture arm64.
