name: Build and lint

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  validation:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install
        run: pnpm install

      - name: Linting
        run: pnpm run lint

      - name: Build on Ubuntu
        run: pnpm run build

      - name: All generated code is commited
        run: |
          git update-index --refresh
          git diff-index --exit-code --name-status HEAD --

  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .github/files/.nvmrc

      - name: NodeJS version
        run: node -v

      - name: PNPM version
        run: pnpm --version

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build
