name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Build
        run: yarn build

  tests:
    name: 20.6.0 Release
    needs: build
    runs-on: ubuntu-18.04
    services:
      eventstore:
        image: eventstore/eventstore:20.6.0-bionic
        env:
          EVENTSTORE_DEV: true
        ports:
          - 2113:2113
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Run Tests
        run: yarn test --ci

  linting:
    name: Linting
    needs: tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Linting
        run: yarn lint