name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Build
        run: yarn build

  tests:
    name: Test
    strategy:
      matrix:
        version: [ci]
    env:
      # Github only passes secrets to the main repo, so we need to skip some things if they are unavailable
      SECRETS_AVAILABLE: ${{ secrets.EVENTSTORE_CLOUD_ID != null }}
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Connect to tailscale
        if: ${{ env.SECRETS_AVAILABLE == 'true' }}
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/eoan.gpg | sudo apt-key add -
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/eoan.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install tailscale
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH }} --hostname "node-client-ci-$(date +'%Y-%m-%dT%H:%M:%S')" --accept-routes
      # Install up to date version of node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: yarn
      - name: Run Tests
        run: yarn test:${{ matrix.version }} --ci --coverage
        env:
          EVENTSTORE_CLOUD_ID: ${{ secrets.EVENTSTORE_CLOUD_ID }}
      - name: Disconnect from tailscale
        if: ${{ env.SECRETS_AVAILABLE == 'true' }}
        run: sudo tailscale down

  package:
    name: Package compiles as a dependency
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Create package
        id: package
        run: |
          echo "::set-output name=package::$(echo $PWD)$(echo "/")$(npm pack)"
          echo "::set-output name=file::$(echo $PWD)$(echo "/.github/files/package_check.txt")"
      - name: Create test project
        run: |
          cd ../
          mkdir ./temp
          cd ./temp
          yarn init -y
          yarn add ${{ steps.package.outputs.package }}
          yarn add --dev typescript
          cp ${{ steps.package.outputs.file }} ./main.ts
      - name: Test project compiles
        working-directory: ../temp
        run: yarn tsc main.ts
          --alwaysStrict
          --noImplicitAny
          --noImplicitReturns
          --strictNullChecks
          --module system
          --moduleResolution node
          --target es2018
          --lib es2020
          --types node
  linting:
    name: Linting
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Linting
        run: yarn lint
