name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Build
        run: yarn build

  tests:
    name: Test
    strategy:
      matrix:
        version: [ci]
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      # Install up to date version of node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: yarn
      - name: Run Tests
        run: yarn test:${{ matrix.version }} --ci

  linting:
    name: Linting
    needs: tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Linting
        run: yarn lint
