name: "Next feature version"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * 0" # Every day at 3am UTC.

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    with:
      cloud_version: "ci"
      esdb_version: "ci"
    secrets:
      eventstore_cloud_id: ${{ secrets.EVENTSTORE_CLOUD_ID }}
      tailscale_auth: ${{ secrets.TAILSCALE_AUTH }}
