name: "EE"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * *" # Every day at 3am UTC.

jobs:
  tests:
    name: "${{ matrix.group.name }}"
    strategy:
      fail-fast: false
      matrix:
        group:
          - name: plugins
            path: ./src/plugins
    env:
      # GitHub only passes secrets to the main repo, so we need to skip some things if they are unavailable
      SECRETS_AVAILABLE: ${{ secrets.EVENTSTORE_CLOUD_ID != null }}
      KURRENT_VERSION: "24.2.0-jammy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .github/files/.nvmrc

      - name: NodeJS version
        run: node -v

      - name: Corepack
        run: corepack enable

      - name: Login to Cloudsmith
        uses: docker/login-action@v3
        with:
          registry: docker.eventstore.com
          username: ${{ secrets.CLOUDSMITH_CICD_USER }}
          password: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}

      - name: Install
        run: yarn

      - name: Corepack
        run: corepack enable

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test ${{ matrix.group.path }} --ci --run-in-band --forceExit
        env:
          KURRENT_IMAGE: eventstore-ee:${{ env.KURRENT_VERSION }}