name: 'previous LTS'

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Every sunday at 3am UTC.

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    with:
      version: '22.10.4-focal'
    secrets:
      eventstore_cloud_id: ${{ secrets.EVENTSTORE_CLOUD_ID }}
      tailscale_auth: ${{ secrets.TAILSCALE_AUTH }}
