name: 'Dispatch'

on:
  workflow_dispatch:
    inputs:
      cloud_version:
        description: 'EventStoreDB server tag'
        required: true
        type: string
      esdb_version:
        description: 'EventStoreDB cloud version tag'
        required: true
        type: string

jobs:
  test:
    name: Test
    uses: ./.github/workflows/tests.yml
    with:
      esdb_version: ${{ inputs.esdb_version }}
      cloud_version: ${{ inputs.cloud_version }}
    secrets:
      eventstore_cloud_id: ${{ secrets.EVENTSTORE_CLOUD_ID }}
      tailscale_auth: ${{ secrets.TAILSCALE_AUTH }}
