name: "LTS"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  test:
    name: Test
    uses: EventStore/EventStore-Client-NodeJS/.github/workflows/tests.yml@master
    with:
      version: "21.10.1-focal"
    secrets:
      eventstore_cloud_id: ${{ secrets.EVENTSTORE_CLOUD_ID }}
      tailscale_auth: ${{ secrets.TAILSCALE_AUTH }}
