name: tests workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      eventstore_cloud_id:
        required: false
      tailscale_auth:
        required: false

jobs:
  tests:
    name: "${{ matrix.group.name }}"
    strategy:
      fail-fast: false
      matrix:
        group:
          - name: samples
            path: ./samples
            tailscale: true

          - name: connection
            path: ./src/__test__/connection
            tailscale: true

          - name: extra
            path: ./src/__test__/extra

          - name: persistentSubscription
            path: ./src/__test__/persistentSubscription

          - name: projections
            path: ./src/__test__/projections

          - name: streams
            path: ./src/__test__/streams
    env:
      # Github only passes secrets to the main repo, so we need to skip some things if they are unavailable
      SECRETS_AVAILABLE: ${{ secrets.eventstore_cloud_id != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Connect to tailscale
        if: ${{ matrix.group.tailscale && env.SECRETS_AVAILABLE == 'true' }}
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/eoan.gpg | sudo apt-key add -
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/eoan.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install tailscale
          sudo tailscale up --authkey ${{ secrets.tailscale_auth }} --hostname "node-client-ci-${{ inputs.version }}-$(date +'%Y-%m-%d-%H-%M-%S')" --advertise-tags=tag:ci --accept-routes
      - uses: actions/setup-node@v4
        with:
          node-version-file: .github/files/.nvmrc
      - name: NodeJS version
        run: node -v
      - name: Install
        run: yarn
      - name: Run Tests
        run: yarn test ${{ matrix.group.path }} --ci --run-in-band --forceExit
        env:
          EVENTSTORE_IMAGE: github:${{ inputs.version }}
          EVENTSTORE_CLOUD_ID: ${{ secrets.eventstore_cloud_id }}
      - name: Disconnect from tailscale
        if: ${{ always() && matrix.group.tailscale && env.SECRETS_AVAILABLE == 'true' }}
        run: sudo tailscale down
